site_name: SON @ ENS Lyon
site_description: ENS Lyon -- Embedded Audio DSP
nav:
  - Lectures:
    - ' 1: Programming Environment Setup ' : lectures/lecture1.md
    - ' 2: Audio Signal Processing Fundamentals ' : lectures/lecture2.md
    - ' 3: Digital Audio Systems Architectures and Audio Callback ' : lectures/lecture3.md
    - ' 4: Hardware Control and Audio Codec Configuration ' : lectures/lecture4.md
    - ' 5: Audio Processing Basics I ' : lectures/lecture6.md
    - ' 6: Embedded basics: interrupts ' : lectures/embedded1.md
    - ' 7: Embedded basics: embedded OS ' : lectures/embedded2.md
    - ' 8: Audio Processing Basics II ' : lectures/lecture7.md
    - ' 9: Introduction to Faust ' : lectures/lecture5.md
    - ' 10: Faust on the Teensy and Advanced Control ' : lectures/lecture8.md
    - ' 11: Some Other Usefull Things to Know ' : lectures/lecture9.md
  - Projects: projects.md
  - Code: "https://github.com/inria-emeraude/son-ens"
    
theme: 
  name: darkly
  navigation_depth: 4

site_dir: ../docs
site_url: https://inria-emeraude.github.io/son-ens/

extra:
    social:
        - type: github
          link: https://inria-emeraude.github.io/son-ens/
        - type: home
          link: https://inria-emeraude.github.io/son-ens/
        - type: envelope
          link: mailto:romain.michon@inria.fr

plugins:
  - search

extra_css: [extra.css]

extra:
  search:
    language: fr

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - markdown_include.include:
        base_path: './docs'
